searchSpaceFile: search_space.json
trialCommand: python main.py
trialGpuNumber: 1
trialConcurrency: 3
maxExecDuration: 10min
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
trainingService:
  platform: local